// Generated by CoffeeScript 1.3.3
(function() {
  var Cookie, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  Cookie = (function() {

    function Cookie() {}

    Cookie.create = function(name, value, days) {
      var date, expires;
      if (days) {
        date = new Date();
        date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
        expires = "; expires=" + (date.toGMTString());
      } else {
        expires = "";
      }
      return document.cookie = "" + name + "=" + (encodeURIComponent(value)) + expires + "; path=/";
    };

    Cookie.read = function(name) {
      var c, ca, i, nameEQ, _i, _ref;
      nameEQ = "" + name + "=";
      ca = document.cookie.split(";");
      for (i = _i = 0, _ref = ca.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        c = ca[i];
        while (c.charAt(0) === ' ') {
          c = c.substring(1, c.length);
        }
        if (c.indexOf(nameEQ) === 0) {
          return decodeURIComponent(c.substring(nameEQ.length, c.length)).replace(/\+/g, ' ');
        }
      }
      return null;
    };

    Cookie.erase = function(name) {
      return this.create(name, "", -1);
    };

    return Cookie;

  })();

  root.Cookie = Cookie;

}).call(this);
